spring:
   application:
      name: com.shuyuan.judd.eureka
   cloud:
      config:
         server:
            git:
               uri: https://github.com/chxfantasy/spring-cloud-demo-config
               search-paths: /app


server:
   port: 1111


eureka:
   server:
      #enable-self-preservation: false
      # 默认 60000 毫秒
      eviction-interval-timer-in-ms: 5000
   client:
      register-with-eureka: true #config server
      fetch-registry: false
      service-url:
         defaultZone: http://127.0.0.1:1111/eureka/
      healthcheck:
         enabled: false
      #Indicates how often(in seconds) to fetch the registry information from the eureka server.
      registry-fetch-interval-seconds: 60
      initial-instance-info-replication-interval-seconds: 5
      eureka-service-url-poll-interval-seconds: 50
   instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      #此配置建议只试用开发和测试环境
      #心跳间隔时间,默认是30秒
      lease-renewal-interval-in-seconds: 6
      #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
      lease-expiration-duration-in-seconds: 60
